services:
  mqtt:
    image: eclipse-mosquitto:2
    ports:
      - "1883:1883"
    volumes:
      - ./test/mosquitto.conf:/mosquitto/config/mosquitto.conf
    healthcheck:
      test: ["CMD-SHELL", "mosquitto_pub -t $$health -m ok || exit 1"]
      interval: 3s
      timeout: 3s
      retries: 10
      start_period: 3s
