services:
  mqtt:
    image: eclipse-mosquitto:2.0.20
    ports:
      - "${MQTT_PORT:-1883}:1883"
    volumes:
      - ./test/mosquitto.conf:/mosquitto/config/mosquitto.conf
    healthcheck:
      test: ["CMD", "mosquitto_sub", "-t", "$$SYS/broker/bytes/received", "-C", "1", "-W", "2"]
      interval: 3s
      timeout: 3s
      retries: 10
      start_period: 3s
